const primary = "#004D36";
const primaryMid = "#006B4A";
const gold = "#C9A02A";

export default {
  light: {
    text: "#0D1B15",
    textSecondary: "#5B7465",
    background: "#F0F5F2",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    tint: primary,
    tintMid: primaryMid,
    tintDark: "#003326",
    gold: gold,
    goldLight: "#FDF3D9",
    tabIconDefault: "#8FA89A",
    tabIconSelected: primary,
    border: "#D4E4DB",
    borderLight: "#E8F0EC",
    statusFree: "#10B981",
    statusFreeLight: "#D1FAE5",
    statusOccupied: "#EF4444",
    statusOccupiedLight: "#FEE2E2",
    statusReserved: "#F59E0B",
    statusReservedLight: "#FEF3C7",
    cardShadow: "rgba(0,77,54,0.08)",
    overlay: "rgba(0,0,0,0.5)",
    headerBg: primary,
    danger: "#EF4444",
    dangerLight: "#FEE2E2",
    success: "#10B981",
    successLight: "#D1FAE5",
    warning: "#F59E0B",
    warningLight: "#FEF3C7",
    info: "#3B82F6",
    infoLight: "#DBEAFE",
    zoneA: "#006B4A",
    zoneALight: "#E0F2EB",
    zoneB: "#0D9373",
    zoneBLight: "#CCEFEA",
    zoneC: gold,
    zoneCLight: "#FDF3D9",
  },
};
