const primary = "#1A6BFF";
const primaryDark = "#0F4FCC";

export default {
  light: {
    text: "#0D1117",
    textSecondary: "#6B7280",
    background: "#F4F6FA",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    tint: primary,
    tintDark: primaryDark,
    tabIconDefault: "#9CA3AF",
    tabIconSelected: primary,
    border: "#E5E7EB",
    borderLight: "#F0F2F5",
    statusFree: "#10B981",
    statusFreeLight: "#D1FAE5",
    statusOccupied: "#EF4444",
    statusOccupiedLight: "#FEE2E2",
    statusReserved: "#F59E0B",
    statusReservedLight: "#FEF3C7",
    cardShadow: "rgba(0,0,0,0.06)",
    overlay: "rgba(0,0,0,0.5)",
    headerBg: "#FFFFFF",
    danger: "#EF4444",
    dangerLight: "#FEE2E2",
    success: "#10B981",
    successLight: "#D1FAE5",
    warning: "#F59E0B",
    warningLight: "#FEF3C7",
    info: "#3B82F6",
    infoLight: "#DBEAFE",
    zoneA: "#6366F1",
    zoneALight: "#EEF2FF",
    zoneB: "#0EA5E9",
    zoneBLight: "#E0F2FE",
    zoneC: "#8B5CF6",
    zoneCLight: "#F5F3FF",
  },
};
